language: go
go:
  - "1.14"
script:
  - export GO111MODULE="on"
  - go install -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
